### ISSUE TITLE
ExpoAsset.downloadAsync Error

### ISSUE THREAD

**Issue by Peud001** [johnpatrick254/bush-x-press-beta#11]
When trying to run the app on expo go app, I encountered this error:  ExpoAsset.downloadAsync is unable to download the SpaceMono-Regular.ttf font file.

Steps to reproduce:
1. Open the project on vs code
2. Type expo start -c on the terminal
3. Scan the QR code using the expo go app and wait for it to load

**Comment by johnpatrick254** [comment]
fixed #10
